pipeline {
    agent { label 'node' }
    tools {
        nodejs 'node-9.5.0-cordova-8'
    }
  
    stages {
        stage('node-build') {
            steps {
                nodejs(configId: 'a49edda1-c1ae-4162-86e0-7ebe47534f01', nodeJSInstallationName: 'node-9.2.0-cordova-6') {
                    sh("npm install")
                    sh("npm whoami")
                }
            }
        }

        stage('node-test') {
            steps {
                nodejs(configId: 'a49edda1-c1ae-4162-86e0-7ebe47534f01', nodeJSInstallationName: 'node-9.2.0-cordova-6') {
                    sh("npm test")
                }
            }
        }

        stage('SonarQube analysis') {
            steps {
                script {
                    scannerHome = tool 'SonarQube Scanner 2.8'
                }
                withSonarQubeEnv('sonar_procergs') {
                    sh "${scannerHome}/bin/sonar-scanner"
                }
            }
        }
        stage('Quality Gate') {
            steps {
                timeout(time: 5, unit: 'MINUTES') {
                    waitForQualityGate abortPipeline: true
                }
            }
        }

        stage('node-publish') {
            steps {
                nodejs(configId: 'a49edda1-c1ae-4162-86e0-7ebe47534f01', nodeJSInstallationName: 'node-9.2.0-cordova-6') {
                    sh("npm publish")
                }
            }
        }
    }
    post {
        always {
            deleteDir()
        }
    }
}
